export const extraBurgerProducts = [
  {
    name: 'Бургер с Луковыми Кольцами',
    description: 'Котлета, хрустящие луковые кольца, сыр и соус барбекю.',
    image: require('../assets/burger_1.jpg'),
    price: 19,
    count: 1,
  },
  {
    name: 'Бургер с Халапеньо',
    description: 'Котлета, сыр, острый халапеньо и соус чили.',
    image: require('../assets/burger_2.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Классический Чизбургер',
    description: 'Говяжья котлета, сыр чеддер, свежие овощи и соус.',
    image: require('../assets/burger_3.jpg'),
    price: 18,
    count: 1,
  },
  {
    name: 'Бургер с Беконом',
    description: 'Котлета, хрустящий бекон, сыр и пикантный соус.',
    image: require('../assets/burger_4.jpg'),
    price: 21,
    count: 1,
  },
  {
    name: 'Бургер с Соусом Рокфор',
    description: 'Котлета, сыр рокфор, салат айсберг и ореховый соус.',
    image: require('../assets/burger_5.jpg'),
    price: 23,
    count: 1,
  },
  {
    name: 'Бургер с Манго',
    description: 'Сочная котлета, ломтики манго, сыр и соус терияки.',
    image: require('../assets/burger_6.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Бургер с Соусом Айоли',
    description: 'Котлета, чесночный соус айоли, свежие овощи и сыр.',
    image: require('../assets/burger_7.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Бургер в Мексиканском Стиле',
    description: 'Котлета, гуакамоле, халапеньо и сыр.',
    image: require('../assets/burger_8.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Бургер с Трюфельным Соусом',
    description: 'Котлета, трюфельный соус, сыр чеддер и рукола.',
    image: require('../assets/burger_9.jpg'),
    price: 25,
    count: 1,
  },
  {
    name: 'Бургер с Грибами',
    description: 'Котлета, жареные шампиньоны, сыр и сливочный соус.',
    image: require('../assets/burger_10.jpg'),
    price: 21,
    count: 1,
  },
  {
    name: 'Бургер с Козьим Сыром',
    description: 'Котлета, козий сыр, карамелизированный лук и руккола.',
    image: require('../assets/burger_11.jpg'),
    price: 24,
    count: 1,
  },
  {
    name: 'Бургер с Соусом Васаби',
    description: 'Котлета, соус васаби, свежие овощи и сыр.',
    image: require('../assets/burger_12.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Бургер с Пармезаном',
    description: 'Котлета, сыр пармезан, соус песто и помидоры.',
    image: require('../assets/burger_13.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Бургер с Оливками',
    description: 'Котлета, ломтики оливок, сыр фета и пикантный соус.',
    image: require('../assets/burger_14.jpg'),
    price: 21,
    count: 1,
  },
  {
    name: 'Бургер с Айсбергом',
    description: 'Котлета, листья салата айсберг, сыр и чесночный соус.',
    image: require('../assets/burger_15.jpg'),
    price: 19,
    count: 1,
  },
  {
    name: 'Бургер с Кукурузой',
    description: 'Котлета, кукуруза, сыр и сливочный соус.',
    image: require('../assets/burger_16.jpg'),
    price: 20,
    count: 1,
  },
  {
    name: 'Бургер со Шпинатом',
    description: 'Котлета, листья шпината, сыр и томатный соус.',
    image: require('../assets/burger_17.jpg'),
    price: 21,
    count: 1,
  },
  {
    name: 'Бургер с Ореховым Соусом',
    description: 'Котлета, ореховый соус, сыр чеддер и свежие овощи.',
    image: require('../assets/burger_18.jpg'),
    price: 22,
    count: 1,
  },
  {
    name: 'Бургер с Двойной Котлетой',
    description: 'Две котлеты, сыр чеддер, бекон и соус барбекю.',
    image: require('../assets/burger_19.jpg'),
    price: 25,
    count: 1,
  },
  {
    name: 'Веганский Бургер',
    description: 'Растительная котлета, свежие овощи, веганский сыр и соус.',
    image: require('../assets/burger_20.jpg'),
    price: 18,
    count: 1,
  },
];
